---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 余思衡.
--- DateTime: 2024/5/15 18:51
---
-- 定义Lua脚本
local key = KEYS[1]
local ttl = ARGV[1]

-- 尝试设置键值对，如果键不存在则设置成功
local result = redis.call('SETNX', key, 1)

-- 如果设置成功，设置过期时间
if result == 1 then
redis.call('EXPIRE', key, ttl)
end

-- 返回结果
return nil
