server:
  port: 8084
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
memo:
    db:
      database: memo-list
rate:
  limit:
    time-unit: seconds
    max-count: 10
    time-range: 60
    strategy: custom

